FilmProject/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace FilmProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

FilmProject/Areas/Admin/Controllers/MovieController.cs
using Bussiness.Exceptions;
using Bussiness.Services.Abstracts;
using Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace FilmProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        public MovieController(IMovieService movieService)
        {
            _movieService= movieService;
        }
        public IActionResult Index()
        {
            var movies =_movieService.GetAllMovies();
            return View(movies);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Movie movie)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                await _movieService.AddMovie(movie);
            }
            catch (ImageContentTypeException ex)
            {
                ModelState.AddModelError("ImageFile", ex.Message);
                return View();
            }
            catch (ImageSizeException ex)
            {
                ModelState.AddModelError("ImageFile", ex.Message);
                return View();
            }
            catch (FileNullReferenceException ex)
            {
                ModelState.AddModelError("ImageFile", ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var existMovie = _movieService.GetMovie(x => x.Id == id);
            if (existMovie == null)
                return View("Error");
            return View(existMovie);
        }
        [HttpPost]
        public IActionResult Update(Movie movie)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                _movieService.UpdateMovie(movie, movie.Id);
            }
            catch (EntityNotFoundException ex)
            {
                return NotFound("Error");
            }
            catch (ImageContentTypeException ex)
            {
                ModelState.AddModelError("ImageFile", ex.Message);
                return View();
            }
            catch (ImageSizeException ex)
            {
                ModelState.AddModelError("ImageFile", ex.Message);
                return View();
            }
            catch (Bussiness.Exceptions.FileNotFoundException ex)
            {
                ModelState.AddModelError("ImageFile", ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }


            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var existMovie = _movieService.GetMovie(x => x.Id == id);
            if (existMovie == null)
                return View("Error");
            return View(existMovie);
        }

        [HttpPost]
        public IActionResult DeletePost(int id)
        {

            try
            {
                _movieService.DeleteMovie(id);
            }
            catch (EntityNotFoundException ex)
            {
                return View("Error");
            }
            catch (Bussiness.Exceptions.FileNotFoundException ex)
            {
                return View("Error");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction("Index");
        }
    }
}

FilmProject/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace FilmProject.Controllers
{
	public class BlogController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

FilmProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FilmProject.Controllers
{
    public class HomeController : Controller
    {
        

        public IActionResult Index()
        {
            return View();
        }

       
    }
}

FilmProject/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;

namespace FilmProject.Controllers
{
	public class OrderController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

FilmProject/Controllers/SingleController.cs
using Microsoft.AspNetCore.Mvc;

namespace FilmProject.Controllers
{
	public class SingleController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

FilmProject/Areas/Admin/Views/Movie/Create.cshtml
@using Core.Models
@model Movie
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" enctype="multipart/form-data">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Name</label>
                    <input asp-for="Name" class="form-control" id="exampleInputEmail1">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Title</label>
                    <input asp-for="Title" class="form-control" id="exampleInputEmail1">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Description</label>
                    <input asp-for="Description" class="form-control" id="exampleInputEmail1">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Director</label>
                    <input asp-for="Director" class="form-control" id="exampleInputEmail1">
                    <span asp-validation-for="Director" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">ReleaseDate</label>
                    <input asp-for="ReleaseDate" class="form-control" id="exampleInputEmail1">
                    <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">ImageFile</label>
                    <input asp-for="ImageFile" class="form-control" id="exampleInputEmail1">
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

FilmProject/Areas/Admin/Views/Movie/Index.cshtml
@using Core.Models
@model List<Movie>
@{
    int counter = 1;
}
<div class="container">
    <div class="row">
        <div class="col-3 mb-3 ">
            <a asp-action="Create" asp-controller="Movie" class="btn btn-outline-primary">Create Movies</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Director</th>
                        <th scope="col">RunningTime</th>
                        <th scope="col">Image</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@(counter++)</th>
                            <td>@item.Name</td>
                            <td>@item.Title</td>
                            <td>@item.Description</td>
                            <td>@item.RunningTime</td>
                            <td>@item.Director</td>
                            <th><img src="~/uploads/movies/@item.ImageUrl" width="50" height="50" /></th>
                            <td>
                                <a asp-action="Update" asp-controller="Movie" asp-route-id="@item.Id" class="btn btn-outline-warning">Update</a>
                                <a asp-action="Delete" asp-controller="Movie" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

FilmProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from template.themeton.com/tenguu-html/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 07 Jun 2024 14:43:19 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <title>Tenguu Cinema - Movie Theater Template</title>
    <meta name="keywords" content="HTML5,CSS3,HTML,Template,Themeton">
    <meta name="description" content="Tenguu Cinema - Movie Theater Template">
    <meta name="author" content="Themeton">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.png" />

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300ita%e2%80%8c%e2%80%8blic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans" />
    <link rel="stylesheet" type="text/css" href="~/css/packages.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/default.css">
</head>
<body class="sticky-menu">
    <div id="loader">
        <div class="loader-ring">
            <div class="loader-ring-light"></div>
            <div class="loader-ring-track"></div>
        </div>
    </div>
    <div class="wrapper">


        <header id="header" class="menu-top-left">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-4">
                        <a href="index.html" id="logo" title="Tenguu" class="logo-image" data-bg-image="images/logo.png">
                            Tenguu
                        </a>
                    </div>
                    <div class="col-md-5 col-md-offset-1 col-sm-6 col-xs-8 phl0">
                        <div class="header_author">
                            <a href="#">Amanda Green</a>
                            <img src="~/images/user.png" class="user" alt="user">
                        </div>
                        <div class="header_ticket">
                            <a href="#order" class="order_btn">My tickets</a>
                            <span>3</span>
                        </div>
                        <a href="javascript:;" id="header-search"></a>
                        <div class="button_container" id="toggle">
                            <span class="top"></span>
                            <span class="middle"></span>
                            <span class="bottom"></span>
                        </div>
                        <div class="overlay" id="overlay">
                            <a href="javascript:;" class="close-window"></a>
                            <nav class="overlay-menu">
                                <ul>
                                    <li><a asp-action="index" asp-controller="home">Home</a></li>
                                    <li><a asp-action="index" asp-controller="blog">Blog</a></li>
                                    <li><a asp-action="index" asp-controller="single">Single</a></li>
                                    <li><a asp-action="index" asp-controller="order">Order</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        @RenderBody()
        <footer id="footer">
            <div class="container footer-container">
                <div class="row">
                    <div class="col-md-2 col-sm-6">
                        <div class="widget">
                            <h5 class="widget-title">Menu</h5>
                            <ul class="menu">
                                <li><a href="#">Home</a></li>
                                <li><a href="#">Coming soon</a></li>
                                <li><a href="#">Order</a></li>
                                <li><a href="#">Terms of service</a></li>
                                <li><a href="#">Pricing</a></li>
                            </ul>
                        </div>
                        <div class="widget">
                            <div class="social-links">
                                <a href="javascript:;"><i class="fa fa-facebook"></i></a>
                                <a href="javascript:;"><i class="fa fa-twitter"></i></a>
                                <a href="javascript:;"><i class="fa fa-google-plus"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="widget">
                            <h5 class="widget-title">Address information</h5>
                            <p>
                                California. AMC Dine-In Theatres Marina,
                                Street 26, Distritc 543 #108
                            </p>
                            <p>
                                <i class="fa fa-mail"></i>Example@mail.com<br>
                                <i class="fa fa-phone"></i> + 123 456 7890
                            </p>
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-6">
                        <div class="widget">
                            <h5 class="widget-title">Leave a message</h5>
                            <form class="contact_form transparent">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <input type="text" class="inputValidation" name="name" placeholder="Name *">
                                    </div>
                                    <div class="col-sm-12">
                                        <input type="text" class="inputValidation" name="email" placeholder="Email *">
                                    </div>
                                    <div class="col-sm-12 ">
                                        <textarea class="inputValidation" placeholder="Message *"></textarea>
                                        <button type="submit" class="button fill rectangle">Send to us</button>
                                    </div>
                                </div>
                            </form>
                            <div class="errorMessage"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="sub-footer">
                <div class="container">
                    <div class="row copyright-text">
                        <div class="col-sm-12 text-center">
                            <p class="mv3 mvt0">&copy; Copyrights 2017 Tenguu. All rights reserved</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <!-- Overlay Search -->
    <div id="overlay-search">
        <form method="get" action="http://template.themeton.com/tenguu-html/">
            <input type="text" name="s" placeholder="Search..." autocomplete="off">
            <button type="submit">
                <i class="fa fa-search"></i>
            </button>
        </form>
        <a href="javascript:;" class="close-window"></a>
    </div>
    <div id="order">
        <div class="container">
            <div class="row order-content">
                <div class="col-sm-8 col-xs-12 seat_content ph0">
                    <h2>order a ticket</h2>
                    <div class="entry-order-content">
                        <form id="msform" name="msform">
                            <!-- fieldsets -->
                            <fieldset>
                                <div class="wpc-content">
                                    <h3>location</h3>
                                    <select name="location">
                                        <option>Tenguu Cinema Tysons corner</option>
                                        <option>Tenguu Cinema </option>
                                        <option>Tenguu Cinema corner</option>
                                        <option>Tenguu Cinema Tysons</option>
                                    </select>
                                    <h3 class="mt3">Movie</h3>
                                    <select>
                                        <option>Dead pool</option>
                                        <option>THE BATTLE OF ALGIERS (DI ALGERI)</option>
                                        <option>LORD OF THE RINGS: THE RETURN OF THE KINGS</option>
                                        <option>Tenguu Cinema Tysons corner</option>
                                    </select>
                                    <h3 class="mt3">Date</h3>
                                    <input type='date' class="datetime" />
                                    <h3 class="mt3">TIME</h3>
                                    <ul class="order-date">
                                        <li><a href="javascript:;"><i>11:50</i></a></li>
                                        <li><a href="javascript:;"><i>13:40</i></a></li>
                                        <li><a href="javascript:;"><i>16:35</i></a></li>
                                        <li><a href="javascript:;"><i>17:30</i></a></li>
                                        <li><a href="javascript:;"><i>19:50</i></a></li>
                                        <li><a href="javascript:;"><i>21:10</i></a></li>
                                    </ul>
                                </div>
                                <input type="button" name="next" class="next action-button" value="Next" />
                            </fieldset>
                            <fieldset class="seat-content">
                                <div class="wpc-content">
                                    <h3 class="seat_title">seat</h3>
                                    <div id="seat-map"></div>
                                    <div id="legend"></div>
                                </div>
                                <input type="button" name="previous" class="action-button previous" value="Previous" />
                                <input type="submit" name="submit" class="submit action-button" value="Submit" />
                            </fieldset>
                        </form>
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12 order_sidebar ph0">
                    <h2>Your Information</h2>
                    <div class="order-details">
                        <span> Location:</span><p id="locationp">Tenguu Cinema Tysons corner</p>
                        <span>Time:</span>  <p>2016.3.8 18:30</p>
                        <span>Seat: </span>
                        <ul id="selected-seats"></ul>
                        <div>Tickets: <span id="counter">0</span></div>
                        <div>Total: <b>$<span id="total">0</span></b></div>
                    </div>
                    <a href="javascript:;" class="close-window"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
    </div>

    <!-- Include jQuery and Scripts -->
    <script type="text/javascript" src="~/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/js/packages.min.js"></script>
    <script type="text/javascript" src="~/js/scripts.min.js"></script>
    <!-- jQuery easing plugin -->
</body>

<!-- Mirrored from template.themeton.com/tenguu-html/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 07 Jun 2024 14:43:19 GMT -->
</html>